name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/*

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Dotnet information
        run: dotnet --info

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        continue-on-error: true
        run: dotnet test --no-build -c Release --logger trx --results-directory "./artifacts"

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: verify-test-results
          path: |
            **/*.received.*

      - name: Process test reports
        uses: im-open/process-dotnet-test-results@v2.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-directory: './artifacts'
