name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/*

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml
          additionalArguments: "/overrideconfig increment=None"

      - name: Build
        run: dotnet build -c Release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }}

      - name: Test
        continue-on-error: true
        run: dotnet test --no-restore --configuration Release --logger trx --results-directory "./artifacts" -v d

      - name: Process test reports
        uses: im-open/process-dotnet-test-results@v2.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-directory: './artifacts'
